language: node_js
node_js:
  - 12.16.3
cache: npm 

install: 
  - npm i

script:
  - npm test
  - npm run
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master